# Uncomment this line to define a global platform for your project
platform :ios, '11.0'

# CocoaPods analytics sends network data synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless defined?(generated_xcode_build_settings_path)
    raise "$INFLUENTIAL_XCODE_BUILD_SETTINGS_PATH was not generated. Running 'pod install' should create the Generated.xcconfig file."
  end
  generated_xcode_build_settings_path = File.expand_path(generated_xcode_build_settings_path)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "Generated.xcconfig must exist. Make sure 'flutter run' works on your project's iOS build."
  end
  flutter_root = File.dirname(File.expand_path(generated_xcode_build_settings_path))
end

# CocoaPods Analytics sends network data synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        'PERMISSION_CAMERA=1',
        'PERMISSION_PHOTOS=1',
        'PERMISSION_NOTIFICATIONS=1',
      ]
    end
  end
end